#!/usr/bin/make -f

all:
	make -C dompi_cloud_notif.cgi
	make -C dompi_cloud_status.cgi
	make -C dompi_cloud_mobile.cgi
	make -C dompi_cloud_auth.cgi
	make -C dompi_cloud_abmuser.cgi
	make -C dompi_cloud_amazon.cgi
	make -C dompi_cloud_alarma.cgi

clean:
	make -C dompi_cloud_notif.cgi clean
	make -C dompi_cloud_status.cgi clean
	make -C dompi_cloud_mobile.cgi clean
	make -C dompi_cloud_auth.cgi clean
	make -C dompi_cloud_abmuser.cgi clean
	make -C dompi_cloud_amazon.cgi clean
	make -C dompi_cloud_alarma.cgi clean

install:
	make -C dompi_cloud_notif.cgi install
	make -C dompi_cloud_status.cgi install
	make -C dompi_cloud_mobile.cgi install
	make -C dompi_cloud_auth.cgi install
	make -C dompi_cloud_abmuser.cgi install
	make -C dompi_cloud_amazon.cgi install
	make -C dompi_cloud_alarma.cgi install

uninstall:
	make -C dompi_cloud_notif.cgi uninstall
	make -C dompi_cloud_status.cgi uninstall
	make -C dompi_cloud_mobile.cgi uninstall
	make -C dompi_cloud_auth.cgi uninstall
	make -C dompi_cloud_abmuser.cgi uninstall
	make -C dompi_cloud_amazon.cgi uninstall
	make -C dompi_cloud_alarma.cgi uninstall
